React route
GSG-G10/udrive-car-rental pull request #115
Opened 2021-10-31 09:58 UTC by AhemdAboAbadi

2021-11-01 17:49 UTC, rawand1998 approved these changes

2021-11-02 07:47 UTC, asmaaamin requested changes

2021-11-02 07:47 UTC, asmaaamin commented on client/src/App/index.js
> +          <li><Link to="/dashboard">booking</Link></li>
```suggestion
          <li><Link to="/dashboard">Dachboard</Link></li>
```

2021-11-02 08:15 UTC, asmaaamin approved these changes

2021-11-02 09:53 UTC, aaamra approved these changes

2021-11-02 09:54 UTC, merged