13 rental form component
GSG-G10/udrive-car-rental pull request #144
Opened 2021-11-02 17:41 UTC by rawand1998

2021-11-05 17:33 UTC, aaamra approved these changes

2021-11-05 18:33 UTC, LinaYahya requested changes

2021-11-05 18:33 UTC, LinaYahya commented on client/src/Components/RentalForm/index.js
> +        console.log(err);
use alert instead

2021-11-05 18:33 UTC, LinaYahya commented on client/src/Components/RentalForm/index.js
> +        await axios.post('/api/v1/rentals/1', {
```suggestion
        await axios.post(`/api/v1/rentals/${id}`, {
```
get id from props

2021-11-05 18:33 UTC, LinaYahya commented on client/src/Components/RentalForm/index.js
> +        <br />
try not to use

2021-11-05 18:33 UTC, LinaYahya commented on client/src/Components/Confirm/inedx.js
> +      <Button loading={false} handelClick={handleClickOpen} text="Rent Now" />
remove button to the form itself

2021-11-05 18:33 UTC, LinaYahya commented on client/src/Components/RentalForm/index.js
> +  const rental = () => {
rename your function to rentCar

2021-11-05 18:33 UTC, LinaYahya commented on client/src/Components/RentalForm/index.js
> +//   id: PropTypes.number.isRequired,
delete those lines

2021-11-05 18:33 UTC, LinaYahya commented on client/src/Components/RentalForm/style.css
> +.container{
rename your className

2021-11-05 18:33 UTC, LinaYahya commented on server/controllers/rentals/addRentalController.js
> +    console.log(err);
```suggestion
```

2021-11-06 07:08 UTC, rawand1998 commented on client/src/Components/RentalForm/index.js
> +        <br />
from eslint

2021-11-06 15:54 UTC, rawand1998 commented on client/src/Components/RentalForm/index.js
> +  const rental = () => {
done

2021-11-06 15:54 UTC, rawand1998 commented on client/src/Components/RentalForm/index.js
> +//   id: PropTypes.number.isRequired,
done

2021-11-06 15:54 UTC, rawand1998 commented on client/src/Components/RentalForm/style.css
> +.container{
done

2021-11-06 15:55 UTC, rawand1998 commented on client/src/Components/RentalForm/index.js
> +        await axios.post('/api/v1/rentals/1', {
done

2021-11-06 15:56 UTC, rawand1998 commented on client/src/Components/RentalForm/index.js
> +        console.log(err);
done

2021-11-07 07:38 UTC, AhemdAboAbadi approved these changes

2021-11-07 09:24 UTC, rawand1998 commented on server/controllers/rentals/addRentalController.js
> +    console.log(err);
done

2021-11-07 12:06 UTC, asmaaamin approved these changes

2021-11-07 12:07 UTC, merged